<template>
  <div class="stats-container">
    <!-- Social Share Section -->
    <div class="share-section mb-20">
      <el-button type="primary" :icon="Share" @click="generateShareCard" :loading="generatingCard">
        Share My Progress
      </el-button>
    </div>

    <!-- Hidden Share Card Template -->
    <div class="share-card-container" ref="shareCardRef">
      <div class="share-card">
        <div class="card-header">
          <div class="app-logo">
            <el-icon :size="40" color="#409eff"><Timer /></el-icon>
            <span>ACIR Focus</span>
          </div>
          <div class="date">{{ new Date().toLocaleDateString() }}</div>
        </div>
        
        <div class="user-info">
          <div class="avatar-placeholder">{{ userStore.user?.username?.charAt(0).toUpperCase() }}</div>
          <div class="user-details">
            <h3>{{ userStore.user?.username }}</h3>
            <span class="level-badge">Lv. {{ userLevel }}</span>
          </div>
        </div>

        <div class="stats-grid">
          <div class="stat-box">
            <span class="value">{{ totalFocusMinutes }}</span>
            <span class="label">Focus Mins</span>
          </div>
          <div class="stat-box">
            <span class="value">{{ completedTasks }}</span>
            <span class="label">Tasks Done</span>
          </div>
          <div class="stat-box">
            <span class="value">{{ streakDays }}</span>
            <span class="label">Day Streak</span>
          </div>
        </div>

        <div class="achievements-preview" v-if="latestAchievement">
          <div class="achievement-pill">
            <el-icon><Medal /></el-icon>
            <span>Latest: {{ latestAchievement.name }}</span>
          </div>
        </div>

        <div class="card-footer">
          <p>Generated by A Clock Inside the Rose</p>
        </div>
      </div>
    </div>

    <!-- Image Preview Dialog -->
    <el-dialog v-model="shareDialogVisible" title="Your Focus Card" width="400px">
      <div class="image-preview">
        <img :src="shareImageUrl" alt="Focus Card" style="width: 100%; border-radius: 8px;" />
      </div>
      <template #footer>
        <span class="dialog-footer">
          <p class="hint-text">Right click or long press to save image</p>
          <el-button @click="shareDialogVisible = false">Close</el-button>
        </span>
      </template>
    </el-dialog>

    <!-- Focus Heatmap Section -->
    <el-card class="mb-20">
      <template #header>
        <span>Focus Heatmap (Yearly)</span>
      </template>
      <div ref="heatmapChartRef" style="height: 200px;"></div>
    </el-card>

    <!-- Achievement Section -->
    <el-card class="mb-20">
      <template #header>
        <span>Achievements</span>
      </template>
      <div class="achievements-grid" v-loading="achievementsLoading">
        <div 
          v-for="achievement in achievements" 
          :key="achievement.id" 
          class="achievement-item"
          :class="{ 'unlocked': achievement.unlocked }"
        >
          <div class="icon-wrapper">
            <el-icon :size="32">
              <component :is="getIcon(achievement.iconName)" />
            </el-icon>
          </div>
          <div class="achievement-info">
            <h4>{{ achievement.name }}</h4>
            <p>{{ achievement.description }}</p>
            <span class="unlock-date" v-if="achievement.unlocked">
              Unlocked: {{ formatDate(achievement.unlockedAt) }}
            </span>
          </div>
        </div>
      </div>
    </el-card>

    <el-row :gutter="20">
      <el-col :span="12">
        <el-card>
          <template #header>
            <span>Focus Time (Last 7 Days)</span>
          </template>
          <div ref="focusChartRef" style="height: 300px;"></div>
        </el-card>
      </el-col>
      <el-col :span="12">
        <el-card>
          <template #header>
            <span>Task Status Distribution</span>
          </template>
          <div ref="taskChartRef" style="height: 300px;"></div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted, computed, watch } from 'vue'
import * as echarts from 'echarts'
import html2canvas from 'html2canvas'
import { getDailyFocusStats, getTaskStatusStats } from '@/api/stats'
import { getUserAchievements, getUserStats } from '@/api/gamification'
import { useUserStore } from '@/stores/user'
import { useThemeStore } from '@/stores/theme'
import { Medal, Trophy, Calendar, Finished, Share, Timer } from '@element-plus/icons-vue'

const userStore = useUserStore()
const themeStore = useThemeStore()
const focusChartRef = ref(null)
const taskChartRef = ref(null)
const heatmapChartRef = ref(null)
let focusChart = null
let taskChart = null
let heatmapChart = null

const achievements = ref([])
const achievementsLoading = ref(false)
const userStats = ref({})

// Share Card Refs
const shareCardRef = ref(null)
const shareDialogVisible = ref(false)
const shareImageUrl = ref('')
const generatingCard = ref(false)

const userLevel = computed(() => userStats.value.level || 1)
const totalFocusMinutes = computed(() => userStats.value.totalFocusMinutes || 0)
const streakDays = computed(() => userStats.value.streakDays || 0)
const completedTasks = ref(0) // Need to fetch this separately or estimate
const latestAchievement = computed(() => {
  return achievements.value.filter(a => a.unlocked).sort((a, b) => new Date(b.unlockedAt) - new Date(a.unlockedAt))[0]
})

// Icon mapping
const getIcon = (name) => {
  const map = {
    'medal': Medal,
    'trophy': Trophy,
    'calendar': Calendar,
    'finished': Finished
  }
  return map[name] || Medal
}

const formatDate = (dateStr) => {
  if (!dateStr) return ''
  return new Date(dateStr).toLocaleDateString()
}

const fetchAllData = async () => {
  if (!userStore.user || !userStore.user.id) return
  
  achievementsLoading.value = true
  try {
    const [achievementsData, statsData, taskStats] = await Promise.all([
      getUserAchievements(userStore.user.id),
      getUserStats(userStore.user.id),
      getTaskStatusStats(userStore.user.id)
    ])
    
    achievements.value = achievementsData || []
    userStats.value = statsData || {}
    
    // Calculate completed tasks from stats
    const doneTaskStat = taskStats.find(s => s.status === 'DONE')
    completedTasks.value = doneTaskStat ? doneTaskStat.count : 0
    
  } catch (e) {
    console.error(e)
  } finally {
    achievementsLoading.value = false
  }
}

const generateShareCard = async () => {
  if (!shareCardRef.value) return
  generatingCard.value = true
  
  try {
    const element = shareCardRef.value.querySelector('.share-card')
    const canvas = await html2canvas(element, {
      scale: 2, // High resolution
      backgroundColor: null,
      logging: false
    })
    
    shareImageUrl.value = canvas.toDataURL('image/png')
    shareDialogVisible.value = true
  } catch (e) {
    console.error('Failed to generate image', e)
  } finally {
    generatingCard.value = false
  }
}

const updateHeatmapOptions = () => {
  if (!heatmapChart) return
  
  const isDark = themeStore.isDark
  
  // Colors
  // Light: Empty=#ebedf0, Heatmap=['#9be9a8', '#40c463', '#30a14e', '#216e39']
  // Optimized Light (Deeper start): ['#ebedf0', '#40c463', '#30a14e', '#216e39', '#10441c']
  
  // Dark: Empty=#2d2d2d (gray), Heatmap=['#0e4429', '#006d32', '#26a641', '#39d353'] (Github Dark)
  // Actually Github Dark uses: #161b22 (empty), #0e4429, #006d32, #26a641, #39d353
  
  // User Feedback: "Ensure even 1 minute is visible"
  // We need to adjust the first color in the range to be distinct from empty color
  // Light Mode Empty: #ebedf0. First Green: #9be9a8. (Good contrast)
  // Dark Mode Empty: #2d2d2d. First Green: #0e4429. (Might be too dark)
  
  // Let's brighten the first step for Dark Mode slightly
  // Using GitHub's actual dark mode palette: #161b22 (bg), #0e4429 (L1), #006d32 (L2), #26a641 (L3), #39d353 (L4)
  // But our bg is #2d2d2d (lighter gray). 
  // #0e4429 is very dark green. On #2d2d2d it might look black.
  // Let's try a lighter green for L1: #1a7f37
  
  const finalDarkColors = ['#2d2d2d', '#238636', '#2ea043', '#3fb950', '#a2d9a7'] // Lighter range for better visibility

  // Re-evaluating Light Mode based on "Deeper start" request
  // Previous: #6cd675 (User thought it was too light? No, "can be deeper")
  // User said: "colors (especially start color...) can be deeper, current is too light"
  // So instead of #9be9a8, let's use something closer to #40c463 as start?
  // Let's shift the whole spectrum darker.
  const lightColorsDeep = ['#ebedf0', '#40c463', '#30a14e', '#216e39', '#0e4429']

  const colors = isDark ? finalDarkColors : lightColorsDeep
  const borderColor = isDark ? '#1a1a1a' : '#ffffff'
  const textColor = isDark ? '#ccc' : '#333'
  const splitLineColor = isDark ? '#333' : '#ccc'

  heatmapChart.setOption({
    visualMap: {
      min: 0,
      max: 120,
      inRange: {
        color: colors
      },
      textStyle: {
        color: textColor
      }
    },
    calendar: {
      itemStyle: {
        borderColor: borderColor,
        borderWidth: 3
      },
      splitLine: {
        lineStyle: {
          color: splitLineColor
        }
      },
      dayLabel: {
        color: textColor
      },
      monthLabel: {
        color: textColor
      }
    },
    series: {
      type: 'heatmap',
      coordinateSystem: 'calendar',
      itemStyle: {
        borderRadius: 3,
        borderColor: borderColor,
        borderWidth: 3
      }
    }
  })
}

// Watch theme changes
watch(() => themeStore.isDark, () => {
  updateHeatmapOptions()
  // Also update other charts if needed (text colors)
  // focusChart?.setOption(...)
})

const initCharts = async () => {
  if (!userStore.user || !userStore.user.id) return

  // 1. Fetch & Render Focus Chart
  if (focusChartRef.value) {
    focusChart = echarts.init(focusChartRef.value)
    focusChart.showLoading()
    
    try {
      const dailyData = await getDailyFocusStats(userStore.user.id)
      const dates = dailyData.map(item => item.date)
      const durations = dailyData.map(item => Math.round(item.totalSeconds / 60))
      
      focusChart.hideLoading()
      focusChart.setOption({
        tooltip: {
          trigger: 'axis',
          axisPointer: { type: 'shadow' }
        },
        grid: {
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        xAxis: {
          type: 'category',
          data: dates,
          axisTick: { alignWithLabel: true }
        },
        yAxis: {
          type: 'value',
          name: 'Minutes'
        },
        series: [
          {
            name: 'Focus Time',
            type: 'bar',
            barWidth: '60%',
            data: durations,
            itemStyle: { color: '#409eff' }
          }
        ]
      })

      // 3. Render Heatmap (Using same daily data)
      if (heatmapChartRef.value) {
        heatmapChart = echarts.init(heatmapChartRef.value)
        const currentYear = new Date().getFullYear()
        
        // Generate full year date range to ensure all days are interactive
        const startDate = new Date(currentYear, 0, 1)
        const endDate = new Date(currentYear, 11, 31)
        const dateMap = new Map()
        
        // Fill map with actual data
        dailyData.forEach(item => {
          dateMap.set(item.date, Math.round(item.totalSeconds / 60))
        })
        
        const heatmapData = []
        for (let d = new Date(startDate); d <= endDate; d.setDate(d.getDate() + 1)) {
          const dateStr = d.toISOString().split('T')[0]
          const value = dateMap.get(dateStr) || 0
          heatmapData.push([dateStr, value])
        }

        heatmapChart.setOption({
          tooltip: {
            position: 'top',
            formatter: (params) => {
              if (params.value[1] === 0) {
                 return `${params.value[0]}: No focus records yet`
              }
              return `${params.value[0]}: ${params.value[1]} mins`
            }
          },
          visualMap: {
            min: 0,
            max: 120, // Max 2 hours for deep color
            calculable: false,
            orient: 'horizontal',
            left: 'center',
            bottom: '0%',
            // Initial colors will be set by updateHeatmapOptions
          },
          calendar: {
            top: 30,
            left: 30,
            right: 30,
            cellSize: ['auto', 13],
            range: currentYear,
            yearLabel: { show: false }
          },
          series: {
            type: 'heatmap',
            coordinateSystem: 'calendar',
            data: heatmapData
          }
        })
        
        // Apply theme styles immediately
        updateHeatmapOptions()
      }

    } catch (e) {
      console.error(e)
      focusChart.hideLoading()
    }
  }

  // 2. Fetch & Render Task Chart
  if (taskChartRef.value) {
    taskChart = echarts.init(taskChartRef.value)
    taskChart.showLoading()
    
    try {
      const statusData = await getTaskStatusStats(userStore.user.id)
      const pieData = statusData.map(item => ({
        name: item.status,
        value: item.count
      }))

      taskChart.hideLoading()
      taskChart.setOption({
        tooltip: {
          trigger: 'item'
        },
        legend: {
          top: '5%',
          left: 'center'
        },
        series: [
          {
            name: 'Task Status',
            type: 'pie',
            radius: ['40%', '70%'],
            avoidLabelOverlap: false,
            itemStyle: {
              borderRadius: 10,
              borderColor: '#fff',
              borderWidth: 2
            },
            label: {
              show: false,
              position: 'center'
            },
            emphasis: {
              label: {
                show: true,
                fontSize: 20,
                fontWeight: 'bold'
              }
            },
            labelLine: { show: false },
            data: pieData
          }
        ]
      })
    } catch (e) {
      console.error(e)
      taskChart.hideLoading()
    }
  }
}

const resizeCharts = () => {
  focusChart?.resize()
  taskChart?.resize()
  heatmapChart?.resize()
}

onMounted(() => {
  initCharts()
  fetchAllData()
  window.addEventListener('resize', resizeCharts)
})

onUnmounted(() => {
  window.removeEventListener('resize', resizeCharts)
  focusChart?.dispose()
  taskChart?.dispose()
  heatmapChart?.dispose()
})
</script>

<style scoped>
.stats-container {
  padding: 20px;
}
.mb-20 {
  margin-bottom: 20px;
}
.share-section {
  display: flex;
  justify-content: flex-end;
}
.achievements-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: 20px;
}
.achievement-item {
  display: flex;
  align-items: center;
  padding: 15px;
  border-radius: 8px;
  background-color: var(--el-fill-color-light);
  border: 1px solid var(--el-border-color-lighter);
  opacity: 0.6;
  filter: grayscale(100%);
  transition: all 0.3s ease;
}
.achievement-item.unlocked {
  opacity: 1;
  filter: grayscale(0%);
  background-color: var(--el-color-success-light-9);
  border-color: var(--el-color-success-light-8);
  box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.1);
}
.icon-wrapper {
  margin-right: 15px;
  color: var(--el-color-success);
  background: var(--el-bg-color);
  padding: 10px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}
.achievement-info h4 {
  margin: 0 0 5px 0;
  font-size: 16px;
  color: var(--el-text-color-primary);
}
.achievement-info p {
  margin: 0;
  font-size: 12px;
  color: var(--el-text-color-secondary);
}
.unlock-date {
  display: block;
  margin-top: 5px;
  font-size: 10px;
  color: var(--el-color-success);
  font-weight: bold;
}
.hint-text {
  font-size: 12px;
  color: var(--el-text-color-secondary);
  margin-right: 10px;
}

/* Share Card Styles (Hidden until generated) */
.share-card-container {
  position: absolute;
  left: -9999px;
  top: -9999px;
}
.share-card {
  width: 400px;
  height: 600px;
  background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
  padding: 30px;
  border-radius: 20px;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  box-shadow: 0 20px 60px rgba(0,0,0,0.1);
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
}
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.app-logo {
  display: flex;
  align-items: center;
  gap: 10px;
  font-weight: bold;
  font-size: 18px;
  color: #303133;
}
.date {
  color: #606266;
  font-size: 14px;
}
.user-info {
  display: flex;
  align-items: center;
  gap: 20px;
  margin-top: 20px;
}
.avatar-placeholder {
  width: 80px;
  height: 80px;
  border-radius: 50%;
  background-color: #409eff;
  color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 36px;
  font-weight: bold;
  box-shadow: 0 4px 10px rgba(64, 158, 255, 0.3);
}
.user-details h3 {
  margin: 0 0 5px 0;
  font-size: 24px;
  color: #303133;
}
.level-badge {
  background-color: #e6a23c;
  color: white;
  padding: 4px 12px;
  border-radius: 12px;
  font-size: 14px;
  font-weight: bold;
}
.stats-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;
  margin: 30px 0;
}
.stat-box {
  background: rgba(255, 255, 255, 0.8);
  padding: 20px;
  border-radius: 16px;
  text-align: center;
  display: flex;
  flex-direction: column;
  box-shadow: 0 4px 12px rgba(0,0,0,0.05);
}
.stat-box:last-child {
  grid-column: span 2;
}
.stat-box .value {
  font-size: 32px;
  font-weight: 800;
  color: #409eff;
}
.stat-box .label {
  font-size: 14px;
  color: #909399;
  margin-top: 5px;
}
.achievements-preview {
  margin-top: auto;
  text-align: center;
}
.achievement-pill {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  background: white;
  padding: 8px 16px;
  border-radius: 20px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.05);
  color: #67c23a;
  font-weight: bold;
}
.card-footer {
  text-align: center;
  font-size: 12px;
  color: #909399;
  margin-top: 30px;
  border-top: 1px solid rgba(0,0,0,0.05);
  padding-top: 15px;
}
</style>
